development:
  adapter: postgresql
  encoding: unicode
  database: theshopapp-dev
  pool: 5
  host: localhost
  username: action
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: theshopapp-test
  pool: 5
  host: localhost
  username: action
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: theshopapp-prod
  pool: 5
  host: localhost
  username: action
  password: